// This file is automatically generated. Do not modify it manually.
// You can publish and connect to a different Firebase project by updating the
// project ID in the studio configuration.
import {
    FirebaseApp,
    getApp,
    getApps,
    initializeApp,
  } from 'firebase/app';
  import {
    Auth,
    getAuth,
  } from 'firebase/auth';
  import {
    Firestore,
    getFirestore,
  } from 'firebase/firestore';

export const firebaseConfig = {
  "projectId": "mymedapp-a3203",
  "appId": "1:28481973536:web:2f854b4a1b91316b96bb45",
  "storageBucket": "mymedapp-a3203.appspot.com",
  "apiKey": "AIzaSyAAJGZzTILo_6N4Re_DIWYBXDotFlr7mIY",
  "authDomain": "mymedapp-a3203.firebaseapp.com",
  "messagingSenderId": "28481973536",
  "measurementId": "G-L94T4J20E2"
};

let firebaseApp: FirebaseApp;
let auth: Auth;
let firestore: Firestore;

export function initializeFirebase(): {
    firebaseApp: FirebaseApp;
    auth: Auth;
    firestore: Firestore;
  } {
    if (getApps().length === 0) {
      firebaseApp = initializeApp(firebaseConfig);
    } else {
      firebaseApp = getApp();
    }
    auth = getAuth(firebaseApp);
    firestore = getFirestore(firebaseApp);
    return { firebaseApp, auth, firestore };
  }
